### ISSUE TITLE
Access denied on TSC TE200

### ISSUE THREAD

**Issue by hayyaun** [tsipiniuk/tsc-ttp-244-pro-webusb-demo#1]
I get access denied error trying to run `.open()` function.

**Comment by tsipiniuk** [comment]
@hayyaun Try to remove VENDOR_ID filters

**Comment by hayyaun** [comment]
I actually did it, and also removed `getDevices()`, but it's not working... the error is on the `.open()` part.
It's a label printer. I guess there is no usb communication defined for this type of printer? I don't know where to look for docs... there is no any

**Comment by tsipiniuk** [comment]
I hope you run the script in Google Chrome. You can see the documentation here  https://wicg.github.io/webusb/

**Comment by hayyaun** [comment]
I do... other devices get connected. but this one not... vendorId is the same as yours. Device brand is TSC TE200

```javascript
/**
 *
 * productId: 626
 * serialNumber: "000001"
 * vendorId: 4611
 *
 * interfaces > 0 > alternate >
 * alternateSetting: 0
 * interfaceClass: 7
 * interfaceProtocol: 2
 * interfaceSubclass: 1
 *
 * ... > endpoints >
 * > 1
 * direction: "out"
 * endpointNumber: 1
 * packetSize: 512
 * type: "bulk"
 * > 2
 * direction: "in"
 * endpointNumber: 2
 * packetSize: 512
 * type: "bulk"
 *
 **/
```

**Comment by tsipiniuk** [comment]
Put a catch exception, see the error. Unfortunately, I can't help you any more, I don't have this model

**Comment by hayyaun** [comment]
catch shows `Uncaught (in promise) DOMException: Failed to execute 'open' on 'USBDevice': Access denied.`

**Comment by hayyaun** [comment]
where to learn that commands language?

**Comment by hayyaun** [comment]
> catch shows `Uncaught (in promise) DOMException: Failed to execute 'open' on 'USBDevice': Access denied.`

I just found out windowsOS needs to rename its modules using `zadig` app to get working with usb printers.
